services:
  app:
    build: ./app
    container_name: app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./images:/app/images
      - ./logs:/app/logs
    networks:
      - front-network
      - back-network
    depends_on:
      - db

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
      - ./images:/images
      - ./logs:/var/log/nginx
    networks:
      - front-network
    depends_on:
      - app

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - image_hosting_data:/var/lib/postgresql/data
    networks:
      - back-network
    restart: always

volumes:
  image_hosting_data:

networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge